import { BOSUT_REFERENCE } from "../research/bosut/reference-document";
import { BOSUT } from "../varieties";
import type { ChecklistItemTemplate, ChecklistPhaseMeta } from "./types";

export const CHECKLIST_PHASES: ChecklistPhaseMeta[] = [
  {
    id: "priprema_zemljista",
    title: "Priprema zemljišta",
    description: "Oranje, analiza i osnovno đubrenje pre sadnje (referentni vodič).",
  },
  {
    id: "sadnja",
    title: "Sadnja",
    description: `Priprema sada, sadnja i herbicid pre nicanja. Rok ${BOSUT.plantingWindowStart}–${BOSUT.plantingWindowEnd}.`,
  },
  {
    id: "navodnjavanje",
    title: "Navodnjavanje",
    description: "Pumpa i sistem kap po kap — dužina creva ≈ ukupna dužina redova.",
  },
  {
    id: "zastita",
    title: "Tretiranje i zaštita",
    description: "Herbicidi, štetočine, bolesti i okvašivač prema referentnom vodiču.",
  },
  {
    id: "berba_skladiste",
    title: "Berba i skladištenje",
    description: "Berba, sušenje i skladištenje prinosa.",
  },
];

export const CHECKLIST_TEMPLATES: ChecklistItemTemplate[] = [
  {
    key: "oranje",
    phase: "priprema_zemljista",
    title: "Oranje",
    description: `Dubina ~${BOSUT_REFERENCE.soilPrep.plowingDepthCm} cm. Površina zavisi od razmaka u redu i između redova.`,
    daysFromPlanting: -14,
    timing: "2–3 nedelje pre sadnje",
    fields: [
      { key: "povrsina_ari", label: "Površina", type: "readonly", autoFrom: "area_ar", unit: "ari" },
      { key: "dubina_cm", label: "Dubina", type: "number", defaultValue: "20", unit: "cm" },
      { key: "termin", label: "Termin", type: "date" },
      { key: "izvodjac", label: "Izvođač", type: "text", placeholder: "Traktor / kooperacija" },
      {
        key: "cena_po_aru",
        label: "Tvoja cena po aru",
        type: "currency",
        unit: "RSD/ari",
        placeholder: "Unesite cenu",
      },
    ],
    costCalc: {
      lines: [{ type: "product", unitKey: "cena_po_aru", qtyKey: "povrsina_ari" }],
    },
  },
  {
    key: "analiza_zemljista",
    phase: "priprema_zemljista",
    title: "Analiza zemljišta",
    description: "Đubrenje isključivo na osnovu analize — obavezno pre osnovne prihrane.",
    daysFromPlanting: -16,
    timing: "Pre đubrenja",
    referenceNote: "Đubrenje na osnovu analize zemljišta.",
    fields: [
      { key: "termin", label: "Termin", type: "date" },
      { key: "ustanova", label: "Ustanova", type: "text", placeholder: "Laboratorija / agrarni savet" },
      { key: "cena", label: "Tvoja cena", type: "currency", placeholder: "Unesite cenu" },
    ],
    costCalc: { lines: [{ type: "field", key: "cena" }] },
  },
  {
    key: "djubrenje",
    phase: "priprema_zemljista",
    title: "Đubrenje — osnovna prihrana",
    description: `NPK ${BOSUT_REFERENCE.fertilization.baseNpkFormulas.join(" / ")} — ${BOSUT_REFERENCE.fertilization.baseNpkKgPerHaMin}–${BOSUT_REFERENCE.fertilization.baseNpkKgPerHaMax} kg/ha. 1/3 azota + sav P i K.`,
    daysFromPlanting: -12,
    timing: "Uz osnovnu obradu",
    referenceNote: BOSUT_REFERENCE.fertilization.sulfur,
    fields: [
      {
        key: "tip",
        label: "Tip đubriva",
        type: "select",
        options: BOSUT_REFERENCE.fertilization.baseNpkFormulas,
        defaultValue: "8:16:24",
      },
      { key: "kolicina_kg", label: "Količina", type: "readonly", autoFrom: "npk_kg", unit: "kg" },
      { key: "termin", label: "Termin", type: "date" },
      {
        key: "cena_po_kg",
        label: "Tvoja cena po kg",
        type: "currency",
        unit: "RSD/kg",
        placeholder: "Unesite cenu",
      },
    ],
    costCalc: {
      lines: [{ type: "product", unitKey: "cena_po_kg", qtyKey: "kolicina_kg" }],
    },
  },
  {
    key: "pumpa",
    phase: "navodnjavanje",
    title: "Pumpa za vodu",
    description: "Pumpa za navodnjavanje — kapacitet prema dužini sistema i broju kapaljki.",
    daysFromPlanting: -7,
    timing: "Pre sadnje",
    fields: [
      { key: "termin", label: "Termin montaže", type: "date" },
      { key: "cena", label: "Tvoja cena pumpe", type: "currency", placeholder: "Unesite cenu" },
      { key: "montaza", label: "Tvoja cena montaže", type: "currency", placeholder: "Unesite cenu" },
    ],
    costCalc: { lines: [{ type: "field", key: "cena" }, { type: "field", key: "montaza" }] },
  },
  {
    key: "kap_po_kap",
    phase: "navodnjavanje",
    title: "Sistem kap po kap",
    description: "Creva po redovima, spojevi, ventili i montaža.",
    daysFromPlanting: -7,
    timing: "Pre sadnje",
    fields: [
      {
        key: "duzina_creva_m",
        label: "Dužina creva",
        type: "readonly",
        autoFrom: "drip_length_m",
        unit: "m",
      },
      { key: "termin", label: "Termin montaže", type: "date" },
      {
        key: "cena_po_m",
        label: "Tvoja cena creva po metru",
        type: "currency",
        unit: "RSD/m",
        placeholder: "Unesite cenu",
      },
      { key: "spojevi", label: "Spojevi i ventili", type: "currency", placeholder: "Unesite cenu" },
      { key: "montaza", label: "Montaža", type: "currency", placeholder: "Unesite cenu" },
    ],
    costCalc: {
      lines: [
        { type: "product", unitKey: "cena_po_m", qtyKey: "duzina_creva_m" },
        { type: "field", key: "spojevi" },
        { type: "field", key: "montaza" },
      ],
    },
  },
  {
    key: "priprema_sadnog_materijala",
    phase: "sadnja",
    title: "Priprema sadnog materijala",
    description: BOSUT_REFERENCE.seedPrep.notes,
    daysFromPlanting: -1,
    timing: "Dan pre sadnje",
    fields: [
      { key: "datum", label: "Datum", type: "date" },
      { key: "trajanje_min", label: "Trajanje potapanja", type: "number", defaultValue: "45", unit: "min" },
      {
        key: "rastvor",
        label: "Rastvor",
        type: "readonly",
        defaultValue: BOSUT_REFERENCE.seedPrep.solution,
      },
      { key: "cena", label: "Tvoja cena (Funomil + Signum)", type: "currency", placeholder: "Unesite cenu" },
    ],
    costCalc: { lines: [{ type: "field", key: "cena" }] },
  },
  {
    key: "sadnja",
    phase: "sadnja",
    title: "Sadnja — mašinska ili ručna",
    description: `Razmak ${BOSUT.spacingCmMin}–${BOSUT.spacingCmMax} cm u redu × ${BOSUT.rowSpacingCmMin}–${BOSUT.rowSpacingCmMax} cm između redova. Dubina ${BOSUT.plantingDepthCmMin}–${BOSUT.plantingDepthCmMax} cm.`,
    daysFromPlanting: 0,
    timing: `${BOSUT.plantingWindowStart} – ${BOSUT.plantingWindowEnd}`,
    referenceNote:
      "Razmak u redu zavisi od kap-po-kap sistema; međuredni — od načina sadnje/berbe i širine guma traktora.",
    fields: [
      { key: "termin", label: "Termin sadnje", type: "date" },
      {
        key: "nacin",
        label: "Način",
        type: "select",
        options: ["Mašinska", "Ručna"],
        defaultValue: "Ručna",
      },
      { key: "izvodjac", label: "Traktor / radnici", type: "text" },
      { key: "povrsina_ari", label: "Površina", type: "readonly", autoFrom: "area_ar", unit: "ari" },
      {
        key: "razmak_u_redu",
        label: "Razmak u redu",
        type: "number",
        defaultValue: String(BOSUT.spacingCm),
        unit: "cm",
      },
      {
        key: "razmak_redova",
        label: "Razmak između redova",
        type: "number",
        defaultValue: String(BOSUT.rowSpacingCm),
        unit: "cm",
      },
      {
        key: "dubina",
        label: "Dubina sadnje",
        type: "number",
        defaultValue: String(BOSUT.plantingDepthCm),
        unit: "cm",
      },
      {
        key: "cena_po_aru",
        label: "Tvoja cena po aru",
        type: "currency",
        unit: "RSD/ari",
        placeholder: "Unesite cenu",
      },
    ],
    costCalc: {
      lines: [{ type: "product", unitKey: "cena_po_aru", qtyKey: "povrsina_ari" }],
    },
  },
  {
    key: "herbicid_stomp",
    phase: "sadnja",
    title: "Herbicid pre nicanja — Stomp aqua",
    description: `${BOSUT_REFERENCE.herbicides.preEmergence.product}, doza ${BOSUT_REFERENCE.herbicides.preEmergence.dose}. Posle sadnje, pre nicanja.`,
    daysFromPlanting: 3,
    timing: "3–7 dana posle sadnje",
    referenceNote: BOSUT_REFERENCE.herbicides.applicationRules.join(" "),
    fields: [
      { key: "termin", label: "Termin", type: "date" },
      { key: "povrsina_m2", label: "Površina", type: "readonly", autoFrom: "area_m2", unit: "m²" },
      { key: "doza", label: "Doza", type: "readonly", defaultValue: BOSUT_REFERENCE.herbicides.preEmergence.dose },
      {
        key: "cena_po_100m2",
        label: "Tvoja cena po 100 m²",
        type: "currency",
        unit: "RSD/100m²",
        placeholder: "Unesite cenu",
      },
    ],
    costCalc: {
      lines: [
        {
          type: "product_scaled",
          unitKey: "cena_po_100m2",
          qtyKey: "povrsina_m2",
          divisor: 100,
        },
      ],
    },
  },
  {
    key: "herbicid_prolece",
    phase: "zastita",
    title: "Prolećni herbicid",
    description: `${BOSUT_REFERENCE.herbicides.spring.product} ${BOSUT_REFERENCE.herbicides.spring.dose}. Alternativa: ${BOSUT_REFERENCE.herbicides.springAlternative.product}.`,
    daysFromPlanting: 150,
    timing: BOSUT_REFERENCE.herbicides.spring.timing,
    referenceNote: BOSUT_REFERENCE.herbicides.spring.note,
    fields: [
      { key: "termin", label: "Termin", type: "date" },
      { key: "povrsina_ha", label: "Površina", type: "readonly", autoFrom: "area_ha", unit: "ha" },
      {
        key: "preparat",
        label: "Preparat",
        type: "select",
        options: [
          BOSUT_REFERENCE.herbicides.spring.product,
          BOSUT_REFERENCE.herbicides.springAlternative.product,
        ],
        defaultValue: BOSUT_REFERENCE.herbicides.spring.product,
      },
      {
        key: "cena_po_ha",
        label: "Tvoja cena po hektaru",
        type: "currency",
        unit: "RSD/ha",
        placeholder: "Unesite cenu",
      },
    ],
    costCalc: {
      lines: [{ type: "product", unitKey: "cena_po_ha", qtyKey: "povrsina_ha" }],
    },
  },
  {
    key: "prolecna_prihrana",
    phase: "zastita",
    title: "Prolećna prihrana azotom",
    description: "Preostali azot + sumpor ((NH4)2SO4 ili fertigacija) kad krene vegetacija.",
    daysFromPlanting: 155,
    timing: "Proleće — početak vegetacije",
    fields: [
      { key: "termin", label: "Termin", type: "date" },
      { key: "preparat", label: "Preparat", type: "text", placeholder: "(NH4)2SO4 / fertigacija" },
      { key: "kolicina_kg", label: "Količina", type: "number", unit: "kg" },
      { key: "cena", label: "Tvoja cena", type: "currency", placeholder: "Unesite cenu" },
    ],
    costCalc: { lines: [{ type: "field", key: "cena" }] },
  },
  {
    key: "lukova_muva",
    phase: "zastita",
    title: "Lukova muva i minirajuća muva",
    description: BOSUT_REFERENCE.pests.onionFly.trap,
    daysFromPlanting: 170,
    timing: "Kraj aprila — početak maja (mlade biljke)",
    referenceNote: `${BOSUT_REFERENCE.pests.onionFly.threshold}. ${BOSUT_REFERENCE.pests.leafMiner.note}`,
    fields: [
      { key: "termin", label: "Termin tretmana", type: "date" },
      {
        key: "preparat",
        label: "Kombinacija",
        type: "select",
        options: [...BOSUT_REFERENCE.pests.onionFly.treatments],
        defaultValue: BOSUT_REFERENCE.pests.onionFly.treatments[0],
      },
      { key: "oprema", label: "Oprema (prskalica)", type: "text" },
      { key: "cena", label: "Tvoja cena tretmana", type: "currency", placeholder: "Unesite cenu" },
    ],
    costCalc: { lines: [{ type: "field", key: "cena" }] },
  },
  {
    key: "okvasivac",
    phase: "zastita",
    title: "Okvašivač Magis",
    description: BOSUT_REFERENCE.sprayerNotes.adjuvant,
    daysFromPlanting: 175,
    referenceNote: BOSUT_REFERENCE.sprayerNotes.general,
    fields: [
      { key: "termin", label: "Termin (prvi tretman)", type: "date" },
      { key: "broj_tretmana", label: "Broj tretmana", type: "number", defaultValue: "4" },
      {
        key: "cena_po_tretmanu",
        label: "Tvoja cena po tretmanu",
        type: "currency",
        unit: "RSD",
        placeholder: "Unesite cenu",
      },
    ],
    costCalc: {
      lines: [{ type: "product", unitKey: "cena_po_tretmanu", qtyKey: "broj_tretmana" }],
    },
  },
  {
    key: "lukova_rdja",
    phase: "zastita",
    title: "Lukova rđa",
    description: BOSUT_REFERENCE.diseases.rust.conditions,
    daysFromPlanting: 200,
    timing: "Proleće — kišni periodi",
    referenceNote: `Kasna sezona: ${BOSUT_REFERENCE.diseases.rust.lateSeason}`,
    fields: [
      { key: "termin", label: "Termin", type: "date" },
      { key: "pracenje", label: "Praćenje (beleške)", type: "text", placeholder: "Simptomi, intenzitet napada" },
      {
        key: "preparat",
        label: "Preparat",
        type: "readonly",
        defaultValue: BOSUT_REFERENCE.diseases.rust.treatment,
      },
      { key: "oprema", label: "Oprema", type: "text" },
      { key: "cena", label: "Tvoja cena tretmana", type: "currency", placeholder: "Unesite cenu" },
    ],
    costCalc: { lines: [{ type: "field", key: "cena" }] },
  },
  {
    key: "trulez",
    phase: "zastita",
    title: "Tretman protiv truleži",
    description: BOSUT_REFERENCE.diseases.rot.timing,
    daysFromPlanting: 240,
    timing: "3–4 nedelje pre vađenja",
    fields: [
      { key: "termin", label: "Termin", type: "date" },
      {
        key: "preparat",
        label: "Preparat",
        type: "select",
        options: [...BOSUT_REFERENCE.diseases.rot.treatments],
        defaultValue: BOSUT_REFERENCE.diseases.rot.treatments[0],
      },
      { key: "oprema", label: "Oprema", type: "text" },
      { key: "cena", label: "Tvoja cena tretmana", type: "currency", placeholder: "Unesite cenu" },
    ],
    costCalc: { lines: [{ type: "field", key: "cena" }] },
  },
  {
    key: "berba",
    phase: "berba_skladiste",
    title: "Berba njive",
    description: "Berba kada je usev spreman — unos dnevnog prinosa ispod.",
    daysFromPlanting: 255,
    timing: "Kraj sezone — planirani datum berbe",
    fields: [
      { key: "termin", label: "Planirani termin berbe", type: "date" },
      { key: "beleska", label: "Beleška", type: "text", placeholder: "Uslovi, napomena" },
    ],
    costCalc: { lines: [] },
  },
  {
    key: "susenje",
    phase: "berba_skladiste",
    title: "Sušenje",
    description: "Sušenje na provetrenom mestu posle berbe.",
    daysFromPlanting: 258,
    timing: "Neposredno posle berbe",
    fields: [
      { key: "termin", label: "Termin", type: "date" },
      { key: "lokacija", label: "Lokacija", type: "text", placeholder: "Suva, provetrena površina" },
    ],
    costCalc: { lines: [] },
  },
  {
    key: "skladistenje",
    phase: "berba_skladiste",
    title: "Skladištenje",
    description: "Skladištenje suvog belog luka, evidencija ukupnog prinosa.",
    daysFromPlanting: 280,
    timing: "Posle sušenja",
    fields: [
      { key: "termin", label: "Termin", type: "date" },
      { key: "lokacija", label: "Skladište", type: "text" },
    ],
    costCalc: { lines: [] },
  },
];

export function getChecklistTemplate(key: string): ChecklistItemTemplate | undefined {
  return CHECKLIST_TEMPLATES.find((t) => t.key === key);
}

export function getTemplatesByPhase(phase: ChecklistPhaseMeta["id"]) {
  return CHECKLIST_TEMPLATES.filter((t) => t.phase === phase);
}
