services:
  - type: web
    name: beli-luk-ekosistem
    runtime: docker
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
