import type { ResearchSource } from "./types";
import { BOSUT_REFERENCE, BOSUT_REFERENCE_ID } from "./reference-document";

/** Kurirani i scrapovani podaci o sorti Bosut — referentni vodič ima prioritet */
export const BOSUT_SOURCES: ResearchSource[] = [
  {
    id: BOSUT_REFERENCE_ID,
    title: BOSUT_REFERENCE.title,
    url: "local://referentni-vodic",
    type: "official",
    language: "sr",
    author: "Referentni agrotehnički vodič",
    scrapedAt: "2026-09-01",
    claims: [
      {
        category: "planting",
        attribute: "rok_sadnje",
        value: `${BOSUT_REFERENCE.planting.windowStart} – ${BOSUT_REFERENCE.planting.windowEnd}`,
        rawText: "Vreme sadnje od 05.10. do 25.10.",
        confidence: "high",
      },
      {
        category: "spacing",
        attribute: "rastojanje_u_redu",
        value: { min: 12, max: 15, unit: "cm" },
        rawText: "U redu 12 do 15 cm.",
        confidence: "high",
      },
      {
        category: "spacing",
        attribute: "rastojanje_izmedju_redova",
        value: { min: 30, max: 50, unit: "cm" },
        rawText: "Između redova 30–50 cm.",
        confidence: "high",
      },
      {
        category: "planting",
        attribute: "dubina_sadnje",
        value: { min: 2, max: 3, unit: "cm" },
        rawText: "Dubina sadnje 2-3 cm.",
        confidence: "high",
      },
      {
        category: "protection",
        attribute: "priprema_sadnog_materijala",
        value: BOSUT_REFERENCE.seedPrep.solution,
        rawText: "Funomil + Signum, 45 min potapanje.",
        confidence: "high",
      },
      {
        category: "fertilization",
        attribute: "npk_osnovna",
        value: `${BOSUT_REFERENCE.fertilization.baseNpkKgPerHaMin}–${BOSUT_REFERENCE.fertilization.baseNpkKgPerHaMax} kg/ha NPK`,
        rawText: "NPK 8:16:24 / 6:12:24 / 7:14:21",
        confidence: "high",
      },
      {
        category: "protection",
        attribute: "herbicid_pre_nicanja",
        value: BOSUT_REFERENCE.herbicides.preEmergence.dose,
        rawText: BOSUT_REFERENCE.herbicides.preEmergence.product,
        confidence: "high",
      },
    ],
  },
  {
    id: "ns-seme-bosut",
    title: "NS Seme — opis sorte Bosut",
    url: "https://prodaja.nsseme.com/povrce-i-cvece/beli-luk/bosut/",
    type: "institute",
    language: "sr",
    author: "Institut za ratarstvo i povrtarstvo, Novi Sad",
    scrapedAt: "2026-09-01",
    claims: [
      {
        category: "registration",
        attribute: "tip_sorte",
        value: "Jesenja (ozima) sorta belog luka",
        rawText: "Jesenja sorta.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "masa_lukovice",
        value: { value: 60, unit: "g" },
        rawText: "Lukovice kompaktne, bele boje, težine oko 60 g.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "masa_cena",
        value: { min: 5, unit: "g" },
        rawText: "Čenovi ujednačeni, težine iznad 5 g.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "sadrzaj_suve_materije",
        value: { max: 35, unit: "%" },
        rawText: "Visok sadržaj suve materije do 35%.",
        confidence: "high",
      },
      {
        category: "economics",
        attribute: "cena_sadnog_materijala",
        value: { value: 825, unit: "RSD/kg" },
        rawText: "Cena: 825 din/kg",
        confidence: "medium",
      },
    ],
  },
  {
    id: "ns-seme-en",
    title: "NS Seme — Bosut (English product page)",
    url: "https://nsseme.com/en/products/vegetables-and-flovers/vegetables/garlic/",
    type: "institute",
    language: "en",
    scrapedAt: "2026-09-01",
    claims: [
      {
        category: "registration",
        attribute: "tip_sorte",
        value: "Autumn cultivar",
        rawText: "Autumn cultivar.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "masa_lukovice",
        value: { value: 60, unit: "g" },
        rawText: "Compact white onion plants, 60 g in weight.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "masa_cena",
        value: { value: 6, unit: "g" },
        rawText: "Cloves are uniform in size, 6 g in weight.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "sadrzaj_suve_materije",
        value: { max: 35, unit: "%" },
        rawText: "High dry matter content, reaching 35%.",
        confidence: "high",
      },
    ],
  },
  {
    id: "ns-seme-savet",
    title: "NS Seme — Nije svaki beli luk Bosut",
    url: "https://nsseme.com/aktuelno/saveti-strucnjaka/nije-svaki-beli-luk-bosut/",
    type: "institute",
    language: "sr",
    author: "Dr Slobodan Vlajić, Dr Vukašin Popović",
    scrapedAt: "2026-09-01",
    claims: [
      {
        category: "registration",
        attribute: "stvorilac",
        value: "Dr Jelica Gvozdenović-Varga, IFVCNS Novi Sad",
        rawText: "Sortu je stvorila dr Jelica Gvozdenović–Varga.",
        confidence: "high",
      },
      {
        category: "registration",
        attribute: "nosilac_prava",
        value: "Institut za ratarstvo i povrtarstvo Novi Sad",
        rawText: "Ovlašćeni nosilac prava za sortu Bosut je IFVCNS.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "masa_cena",
        value: { value: 6, unit: "g" },
        rawText: "Ujednačeni čenovi prosečne mase oko 6 g.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "masa_lukovice",
        value: { value: 60, unit: "g" },
        rawText: "Kompaktne lukovice težine oko 60 g.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "sadrzaj_suve_materije",
        value: { value: 36, unit: "%" },
        rawText: "Sadržaj suve materije od 36%.",
        confidence: "high",
      },
      {
        category: "general",
        attribute: "sertifikovani_sadni_materijal",
        value: "Obavezan — neovlašćen promet krši Zakon o semenu RS",
        rawText: "Promet sadnog materijala sorte Bosut od strane neovlašćenih lica predstavlja kršenje zakona.",
        confidence: "high",
      },
      {
        category: "disease",
        attribute: "rizik_bolesti",
        value: "Visok — vegetativno razmnožavanje, osetljiv na mikroze i viroze",
        rawText: "Beli luk se razmnožava vegetativno, čenovima, što ga čini posebno osetljivim na bolesti.",
        confidence: "high",
      },
    ],
  },
  {
    id: "kurir-2014",
    title: "Kurir — Bosut jesenji beli luk",
    url: "https://www.kurir.rs/vesti/srbija/1556935/bosut-jesenji-beli-luk",
    type: "media",
    language: "sr",
    publishedAt: "2014-09-16",
    author: "IFVCNS (citirano)",
    scrapedAt: "2026-09-01",
    claims: [
      {
        category: "planting",
        attribute: "rok_sadnje",
        value: { min: 5, max: 25, unit: "oktobar (dan)" },
        rawText: "Optimalan rok sadnje od 5.10. do 25.10.",
        confidence: "high",
      },
      {
        category: "planting",
        attribute: "pokrivni_sloj",
        value: { min: 2, max: 3, unit: "cm iznad vrha čena" },
        rawText: "Pokrovnog sloja 2-3 cm iznad vrha čena.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "oblik_lukovice",
        value: "Kompaktna, pljosnato-okrugla, bela, ~60 g, dobro zatvoren vrat",
        rawText: "Lukovice kompaktne, pljosnato-okruglog oblika, bele boje, težine oko 60 grama.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "broj_cenova",
        value: { min: 8, max: 10, unit: "kom" },
        rawText: "Broj čenova je od 8 do 10.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "sadrzaj_suve_materije",
        value: { min: 36, unit: "%" },
        rawText: "Sadržaj suve materije je preko 36%.",
        confidence: "high",
      },
      {
        category: "general",
        attribute: "namena",
        value: "Industrijska prerada i sveža upotreba",
        rawText: "Pogodan je za industrisku preradu i svežu upotrebu.",
        confidence: "high",
      },
    ],
  },
  {
    id: "ifvcns-2000",
    title: "IFVCNS — Karakteristike priznatih sorti povrća 2000",
    url: "https://fiver.ifvcns.rs/handle/123456789/251",
    type: "scientific",
    language: "sr",
    author: "Jelica Gvozdenović-Varga, Mirjana Vasić",
    publishedAt: "2000",
    scrapedAt: "2026-09-01",
    claims: [
      {
        category: "registration",
        attribute: "godina_priznanja",
        value: "2000",
        rawText: "Sorte povrća priznate 2000. godine — Bosut.",
        confidence: "high",
      },
      {
        category: "registration",
        attribute: "metod_stvaranja",
        value: "Klonska selekcija",
        rawText: "Bosut | Klonska selekcija | Jelica Gvozdenović-Varga",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "visina_biljke",
        value: { min: 70, max: 75, unit: "cm" },
        rawText: "Bosut je visine biljke 70-75 cm.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "masa_lukovice",
        value: { value: 80, unit: "g" },
        rawText: "Lukovica bele boje, težine oko 80 g.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "broj_cenova",
        value: { min: 12, max: 14, unit: "kom" },
        rawText: "Lukovica je sa 12-14 čenova.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "masa_cena",
        value: { value: 6, unit: "g" },
        rawText: "Čenovi prosečne mase oko 6 grama.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "sadrzaj_suve_materije",
        value: { min: 38, unit: "%" },
        rawText: "Sadržaj suve materije iznad 38%.",
        confidence: "high",
      },
      {
        category: "yield",
        attribute: "prinos",
        value: "Veoma visok prinos na oba ispitivana lokaliteta",
        rawText: "U obe godine ispitivanja ostvarila je veoma visok prinos.",
        confidence: "medium",
      },
    ],
  },
  {
    id: "agrosmart-2016",
    title: "AgroSmart — intervju sa dr Jelenom Gvozdenović Varga",
    url: "https://agrosmart.net/2016/11/07/beli-luk-papreno-skup-a-jos-cemo-jesti-kineski/",
    type: "media",
    language: "sr",
    author: "Dr Jelena Gvozdenović Varga",
    publishedAt: "2016-11-07",
    scrapedAt: "2026-09-01",
    claims: [
      {
        category: "registration",
        attribute: "eu_sortna_lista",
        value: "Na sortnoj listi EU (2016)",
        rawText: "Od ove godine i na sortnoj listi Evropske unije.",
        confidence: "medium",
      },
      {
        category: "registration",
        attribute: "godina_priznanja_rs",
        value: "2001",
        rawText: "Priznata još 2001. godine.",
        confidence: "high",
      },
      {
        category: "yield",
        attribute: "prinos",
        value: { min: 10000, max: 12000, unit: "kg/ha" },
        rawText: "Prinos te sorte u Srbiji je od 10 do 12 tona.",
        confidence: "high",
      },
      {
        category: "economics",
        attribute: "ulaganje_po_ha",
        value: { min: 4000, max: 5000, unit: "EUR/ha" },
        rawText: "Za hektar treba dati 4.000-5.000 evra zbog količine sadnog materijala.",
        confidence: "medium",
      },
      {
        category: "planting",
        attribute: "kolicina_sadnog_materijala",
        value: { min: 500, max: 1200, unit: "kg/ha" },
        rawText: "Od 500 do 1.200 kilograma, pa i više, u zavisnosti od krupnoće čenova.",
        confidence: "high",
      },
      {
        category: "general",
        attribute: "uniformnost_cenova",
        value: "Nema razlike između spoljnih i unutrašnjih — cela glavica iskoristiva",
        rawText: "Čenovi ujednačene veličine, nema razlike između spoljnih i unutrašnjih.",
        confidence: "high",
      },
    ],
  },
  {
    id: "agroinfonet",
    title: "Agro Info Net — uzgoj belog luka (Bosut)",
    url: "https://agroinfonet.com/poljoprivreda/povrtarstvo/beli-luk/",
    type: "practical",
    language: "sr",
    scrapedAt: "2026-09-01",
    claims: [
      {
        category: "planting",
        attribute: "rok_sadnje",
        value: "Od početka do kraja oktobra",
        rawText: "Jesenja sadnja od početka i traje do kraja oktobra.",
        confidence: "high",
      },
      {
        category: "spacing",
        attribute: "sistem_sadnje",
        value: "6-redne trake: 20 cm između redova, posle 6. reda razmak 50 cm, u redu 10 cm",
        rawText: "Šestorede trake, 20 cm red od reda, posle šestog reda 50 cm, u redu 10 cm.",
        confidence: "high",
      },
      {
        category: "spacing",
        attribute: "rastojanje_basta",
        value: "30–40 cm između redova, 10–12 cm u redu",
        rawText: "Sadnja u baštama 30–40 cm između redova, u redu 10–12 cm.",
        confidence: "high",
      },
      {
        category: "planting",
        attribute: "kolicina_sadnog_materijala",
        value: { min: 1400, max: 1600, unit: "kg/ha" },
        rawText: "Kod jesenjeg belog luka se kreće 1400–1600 kg/ha.",
        confidence: "high",
      },
      {
        category: "yield",
        attribute: "prinos_sem_proizvodnja",
        value: { value: 9000, unit: "kg/ha" },
        rawText: "Ostvareni prinos 4.500 kg na 0,5 ha (semenska proizvodnja, Zmajevo).",
        confidence: "high",
      },
      {
        category: "harvest",
        attribute: "rok_berbe",
        value: "Prva polovina jula (jesenja sadnja)",
        rawText: "Beli luk jesenje sadnje obično se vadi u prvoj polovini jula.",
        confidence: "high",
      },
      {
        category: "storage",
        attribute: "trajanje_skladistenja",
        value: { min: 4, max: 6, unit: "meseci" },
        rawText: "Onaj koji se sadi u jesen koristi se 4-6 meseci.",
        confidence: "high",
      },
    ],
  },
  {
    id: "agrovesti-damljanovic",
    title: "AgroVesti / PSSS — Milan Damljanović, sadnja ozimog luka",
    url: "https://agrovesti.rs/sadnja-ozimog-belog-luka/",
    type: "official",
    language: "sr",
    author: "dipl.ing. Milan Damljanović, PSSS",
    scrapedAt: "2026-09-01",
    claims: [
      {
        category: "general",
        attribute: "preporucena_sorta",
        value: "Bosut — domaća sorta za srpske agroekološke uslove",
        rawText: "Kao najbolja preporučuje domaća sorta bosut.",
        confidence: "high",
      },
      {
        category: "fertilization",
        attribute: "jesenja_prihrana",
        value: { min: 400, max: 500, unit: "kg/ha NPK 8-16-24" },
        rawText: "Uneti oko 400–500 kg NPK-8-16-24 pri osnovnoj obradi.",
        confidence: "high",
      },
      {
        category: "fertilization",
        attribute: "prolecna_prihrana",
        value: { min: 400, max: 500, unit: "kg/ha NPK 15-15-15 (februar)" },
        rawText: "Početkom februara istu količinu NPK-15-15-15.",
        confidence: "high",
      },
      {
        category: "fertilization",
        attribute: "stajnjak",
        value: "Ne đubriti stajnjakom pre setve — više vode u lukovici, brže kvarenje",
        rawText: "Pred setvu nikako ne treba đubriti stajnjakom.",
        confidence: "high",
      },
      {
        category: "general",
        attribute: "plodored",
        value: "Ne posle kukuruza i šećerne repe; najbolji: mahunarke, strnine, paradajz, paprika; ponovo luk posle 4–5 godina",
        rawText: "Beli luk može na isto mesto posle drugih lukova tek nakon 4-5 godina.",
        confidence: "high",
      },
      {
        category: "planting",
        attribute: "rok_sadnje",
        value: "Prva polovina oktobra",
        rawText: "Optimalni rok sadnje za jesenji luk je prva polovina oktobra.",
        confidence: "high",
      },
      {
        category: "planting",
        attribute: "pokrivni_sloj",
        value: { min: 2, max: 3, unit: "cm iznad vrha čena" },
        rawText: "Pokrovni sloj 2–3 cm iznad vrha čena.",
        confidence: "high",
      },
      {
        category: "spacing",
        attribute: "rastojanje_redova",
        value: { min: 40, max: 50, unit: "cm" },
        rawText: "Rastojanje između redova 40–50 cm.",
        confidence: "high",
      },
      {
        category: "spacing",
        attribute: "rastojanje_u_redu",
        value: { min: 7, max: 10, unit: "cm" },
        rawText: "U redu 7–10 cm.",
        confidence: "high",
      },
      {
        category: "planting",
        attribute: "kolicina_sadnog_materijala",
        value: { min: 1400, max: 1800, unit: "kg/ha" },
        rawText: "1.400–1.800 kg čenova po hektaru.",
        confidence: "high",
      },
      {
        category: "protection",
        attribute: "tretman_pre_sadnje",
        value: "Fungicidi cineb/ditan, 10–20 min, pa sušenje",
        rawText: "Tretiraju fungicidima (cineb, ditan) 10-20 minuta.",
        confidence: "high",
      },
      {
        category: "protection",
        attribute: "herbicidi",
        value: "Stomp 330 EC 4–5 l/ha pre nicanja; Goal 0.4–0.8 l/ha u fazi 4–5 listova",
        rawText: "Stomp 330 EC posle sadnje; Goal kasnije.",
        confidence: "medium",
      },
      {
        category: "protection",
        attribute: "plamenjaca",
        value: "Cineb, Ditan, Ridomil — preventivno",
        rawText: "Tretiranje protiv plamenjače preparatima Cineb, Ditan, Ridomil.",
        confidence: "medium",
      },
      {
        category: "harvest",
        attribute: "berba",
        value: "Početna faza poleganja, list još zelen; obavezno podrivanje",
        rawText: "Branje u početnoj fazi poleganja, list još zelen.",
        confidence: "high",
      },
      {
        category: "storage",
        attribute: "trajanje_skladistenja",
        value: { max: 6, unit: "meseci" },
        rawText: "Beli luk iz jesenje sadnje se može čuvati do šest meseci.",
        confidence: "high",
      },
    ],
  },
  {
    id: "totic-canak-2014",
    title: "Ekonomika poljoprivrede — Totić & Čanak, poređenje sorti (Bosut)",
    url: "https://doi.org/10.5937/ekopolj1404915t",
    type: "scientific",
    language: "en",
    author: "Ibrahim Totić, Stevan Čanak",
    publishedAt: "2014",
    scrapedAt: "2026-09-01",
    claims: [
      {
        category: "planting",
        attribute: "datum_sadnje",
        value: "8–9. oktobar 2013 (Arilje, Novi Pazar)",
        rawText: "Planting October 8th Arilje, October 9th Novi Pazar.",
        confidence: "high",
      },
      {
        category: "planting",
        attribute: "dubina_sadnje",
        value: { min: 4, max: 6, unit: "cm (dubina rupe)" },
        rawText: "Small planting rows at depth between 4 and 6 cm.",
        confidence: "high",
      },
      {
        category: "planting",
        attribute: "pokrivni_sloj",
        value: { min: 2, max: 3, unit: "cm zemlje iznad čena" },
        rawText: "Covered with layer of soil approximately 2 to 3 cm thick.",
        confidence: "high",
      },
      {
        category: "spacing",
        attribute: "rastojanje_u_redu",
        value: { min: 10, max: 11, unit: "cm" },
        rawText: "Distance between 10 and 11 cm.",
        confidence: "high",
      },
      {
        category: "spacing",
        attribute: "rastojanje_redova",
        value: { min: 45, unit: "cm (međured za pristup)" },
        rawText: "Pathway between rows 45 cm wide.",
        confidence: "high",
      },
      {
        category: "yield",
        attribute: "prinos_arilje",
        value: { value: 876, unit: "kg / ~64 m² parcela" },
        rawText: "Highest yield on plot A: Bosut 87.6 kg.",
        confidence: "high",
      },
      {
        category: "yield",
        attribute: "prinos_novi_pazar",
        value: { value: 892, unit: "kg / ~80 m² parcela" },
        rawText: "Highest yield on plot B: Bosut 89.2 kg.",
        confidence: "high",
      },
      {
        category: "yield",
        attribute: "odnos_prinosa",
        value: "8.3:1 (prinos : sadni materijal) — najbolji među 4 sorte",
        rawText: "Overall yield : seed material 8.3 : 1 for Bosut on plot A.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "masa_lukovice_berba",
        value: { value: 37.8, unit: "g (prosek posle berbe, ogled)" },
        rawText: "Average weight of one bulb 37.8 g (Arilje).",
        confidence: "medium",
      },
      {
        category: "economics",
        attribute: "cena_trziste",
        value: { min: 250, max: 400, unit: "RSD/kg (Bosut)" },
        rawText: "Bosut type costs from 250 RSD/kg to over 400 RSD/kg.",
        confidence: "medium",
      },
      {
        category: "harvest",
        attribute: "duzina_vegetacije",
        value: { value: 9, unit: "meseci u zemlji" },
        rawText: "Garlic spent full nine months in the ground.",
        confidence: "high",
      },
      {
        category: "storage",
        attribute: "gubitak_mase_susenje",
        value: { min: 30, max: 40, unit: "%" },
        rawText: "Garlic loses between 30% and 40% of mass from extraction to sale.",
        confidence: "medium",
      },
    ],
  },
  {
    id: "plodna-zemlja-tatjana",
    title: "Plodna Zemlja — proizvođač Bosut, Banatski Dvor",
    url: "https://plodnazemlja.com/2023/09/21/tatjana-mandic-iz-banatskog-dvora-nastavili-smo-tradiciju-bake-koje-je-sadila-domacu-sortu-belog-luka-bosut-koja-odlicno-radja-i-otporna-je-na-vremenske-uslove-i-bolesti/",
    type: "practical",
    language: "sr",
    author: "Tatjana Mandić",
    publishedAt: "2023-09-21",
    scrapedAt: "2026-09-01",
    claims: [
      {
        category: "yield",
        attribute: "prinos_basta",
        value: { value: 160, unit: "kg / 150 m² (6×25 m)" },
        rawText: "Prinos od oko 160 kilograma na površini od 6×25 metara.",
        confidence: "high",
      },
      {
        category: "planting",
        attribute: "rok_sadnje",
        value: "Sredina oktobra",
        rawText: "Beli luk se sadi sredinom oktobra.",
        confidence: "medium",
      },
      {
        category: "planting",
        attribute: "dubina_sadnje",
        value: { min: 10, max: 15, unit: "cm (iz prakse proizvođača)" },
        rawText: "Češanj se sadi na oko 10-15 cm dubine.",
        confidence: "low",
      },
      {
        category: "general",
        attribute: "otpor_bolestima",
        value: "Visok — bez oboljenja u praksi, organski uzgoj",
        rawText: "Bosut je otporan. Do sada nije bilo nikakvog obolevanja.",
        confidence: "medium",
      },
      {
        category: "economics",
        attribute: "prodajna_cena",
        value: { value: 650, unit: "RSD/kg (organski)" },
        rawText: "Kupci naručuju po 650 dinara za kilogram.",
        confidence: "medium",
      },
      {
        category: "harvest",
        attribute: "berba",
        value: "Kad su stabljike poluzelene/polužute; vaditi pa sušiti u buntovima 2+ nedelje",
        rawText: "Vadimo kada su stabljike poluzelene dovoljno žute da je zreo.",
        confidence: "medium",
      },
      {
        category: "storage",
        attribute: "skladistenje",
        value: "Suvo, tamno, promaja; konzervacija poželjna tokom godine",
        rawText: "Do zime čuvanje u suvom i tamnom mestu, na promaji.",
        confidence: "medium",
      },
    ],
  },
  {
    id: "ekapija-tatjana",
    title: "eKapija — Bosut otporan na bolesti",
    url: "https://www.ekapija.com/where-to-invest/4390089/stara-domaca-sorta-belog-luka-otporna-na-bolesti-stabilni-prinos-i-zarada",
    type: "media",
    language: "sr",
    publishedAt: "2023",
    scrapedAt: "2026-09-01",
    claims: [
      {
        category: "general",
        attribute: "otpor",
        value: "Otpornost na vremenske uslove i bolesti (anegdotski)",
        rawText: "Bosut je otporan i rađa.",
        confidence: "low",
      },
      {
        category: "morphology",
        attribute: "masa_lukovice",
        value: { value: 60, unit: "g" },
        rawText: "Lukovice težine oko 60 grama.",
        confidence: "high",
      },
      {
        category: "morphology",
        attribute: "broj_cenova",
        value: { min: 8, max: 10, unit: "kom" },
        rawText: "U lukovici ima od osam do deset čenova.",
        confidence: "high",
      },
    ],
  },
  {
    id: "ifvcns-garlic-paper",
    title: "IFVCNS — Garlic production from planting material aspect",
    url: "https://fiver.ifvcns.rs/handle/123456789/721",
    type: "scientific",
    language: "en",
    author: "J. Varga et al.",
    publishedAt: "2009",
    scrapedAt: "2026-09-01",
    claims: [
      {
        category: "general",
        attribute: "povrsina_srbija",
        value: { value: 9000, unit: "ha godišnje" },
        rawText: "Garlic produced on about 9,000 ha annually in Serbia.",
        confidence: "high",
      },
      {
        category: "general",
        attribute: "sertifikovani_materijal",
        value: "Ključan za povećanje prosečnog prinosa u Srbiji",
        rawText: "Requires modern varieties and certified planting material.",
        confidence: "high",
      },
    ],
  },
];
